name: Build Metabase ARM64 Image

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - .github/workflows/build-arm64.yml

jobs:
  build-arm64:
    name: Build & Push ARM64 Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image (ARM64)
        id: buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/metabase-arm64:latest

      - name: Image digest
        run: echo "Built image digest is ${{ steps.buildx.outputs.digest }}"
